### PR TITLE
chore: Add npm maintainers

### PR DESCRIPTION
**Pull request by RichardLitt**
This adds a maintainers field to the package.json. Ideally, someone else should be in this field, too. Please add another contributor as a maintainer for this npm package, such as @shamb0t, by typing: `npm owner add @shamb0t`. Then, add them to the maintainers field in this PR, or ping me to do it. Thank you.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hold off on this. There's an issue with inconsistent docs for npm's package.json. Looking into it.

**Comment by RichardLitt** [comment]
Figured out a workaround. In keeping with orbitdb/welcome#55, I add an orbitdb field here. I also suggest @shamb0t as an extra maintainer, as she is already a contributor here. When this is merged, she should be added.

@haadcode Let me know if this works. If it does, I'll go through and do similar PRs to the rest of the org.

**Comment by aphelionz** [comment]
In this, is the `orbitdb` key arbitrary or does that map to an npm org?

**Comment by RichardLitt** [comment]
It's arbitrary. It's just for us to use. `maintainer` and `maintainers` at the top-level might be an issue.

**Comment by aphelionz** [comment]
How is the array of names in `orbitdb.maintainers` consumed on the NPM side?

**Comment by RichardLitt** [comment]
It isn't. I'd like to build a tool to check the veracity of the maintainers list against the `npm info` output. For lack of a better space, I opened an issue about that here: https://github.com/orbitdb/repo-template/issues/6. For now, I'd manually check it.

**Comment by aphelionz** [comment]
aha! ok. Then go wild, my friend

**Comment by shamb0t** [comment]
LGTM :+1:

**Comment by haadcode** [comment]
Updated my email, good to go 👍

**Pull request merged**
